
name: Update gist with WakaTime stats

on:
  push:
     branches: [master]
  pull_request:
     branches: [master]
  schedule:
    - cron: "5 0 * * *"  # 每天 UTC 05:00 运行
    #- cron: "*/5 * * * *"  # 调试用，正式使用改为 "0 0 * * *"

jobs:
  build:
    name: Update-gist
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN_WA }}
      GIST_ID: b03a8abcd73cb837b741fe4fe1ad5997
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史以便变基
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - name: Clone and run waka-box
        run: |-
          git clone https://github.com/Saika-Z/waka-box-go.git 
          cd waka-box-go && go build -o waka ./cmd/box/main.go
          mv ./waka ../ && cd .. && rm -rf waka-box-go/

      - name: Commit and push
        run: |-
           # 配置 Git 用户信息和合并策略
           git config --global user.email "bot@github.com"
           git config --global user.name "Waka-Bot"
           git config pull.rebase true  # 设置默认合并策略为变基
           
           # 拉取最新代码（自动使用 rebase）
           git pull origin main
           
           # 生成新内容
           ./waka
           
           # 提交并推送
           git diff
           git add README.md
           git commit -m ":memo: update profile" || exit 0
           git push origin main

          
